[package]
org = "janud"
name = "support_chat"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.14.3"

[[dependency]]
org = "ballerina"
name = "websocket" 
version = "2.14.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.9.1"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.1"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.1"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.1.0"

[tool.bal]
central.accessToken = ""